export const AGENT_MODEL_PROVIDERS = [
  {
    id: 'claude',
    name: 'Claude',
    vendor: 'Anthropic',
    description: 'Strong reasoning, safety-focused. Best for complex workflows.',
    modelIds: [
      'claude-sonnet-4-6',
      'claude-opus-4-7',
      'claude-opus-4-6',
      'claude-haiku-4-5-20251001',
      'claude-haiku-4-5',
    ],
  },
  {
    id: 'codex',
    name: 'Codex',
    vendor: 'OpenAI',
    description: 'Code-first agent model. Good for dev-oriented tasks.',
    modelIds: [
      'gpt-5.5',
      'gpt-5.5-pro',
      'gpt-5.4',
      'gpt-5.4-pro',
      'gpt-5.4-mini',
      'gpt-5.4-nano',
      'gpt-5.3-codex',
      'gpt-5.3-codex-spark',
      'gpt-5.2-codex',
      'gpt-5.2',
      'gpt-5.1-codex-max',
      'gpt-5.1',
      'gpt-5.1-codex',
      'gpt-5-codex',
      'gpt-5-codex-mini',
      'gpt-5',
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vendor: 'Cursor',
    description: 'Headless Cursor Agent CLI with current server-relevant model IDs.',
    modelIds: [
      'composer-2.5-fast',
      'composer-2.5',
      'composer-2-fast',
      'composer-2',
      'auto',
      'gpt-5.3-codex-low',
      'gpt-5.3-codex-low-fast',
      'gpt-5.3-codex',
      'gpt-5.3-codex-fast',
      'gpt-5.3-codex-high',
      'gpt-5.3-codex-high-fast',
      'gpt-5.3-codex-xhigh',
      'gpt-5.3-codex-xhigh-fast',
      'gpt-5.2',
      'gpt-5.2-codex-low',
      'gpt-5.2-codex-low-fast',
      'gpt-5.2-codex',
      'gpt-5.2-codex-fast',
      'gpt-5.2-codex-high',
      'gpt-5.2-codex-high-fast',
      'gpt-5.2-codex-xhigh',
      'gpt-5.2-codex-xhigh-fast',
      'gpt-5.1-codex-max-low',
      'gpt-5.1-codex-max-low-fast',
      'gpt-5.1-codex-max-medium',
      'gpt-5.1-codex-max-medium-fast',
      'gpt-5.1-codex-max-high',
      'gpt-5.1-codex-max-high-fast',
      'gpt-5.1-codex-max-xhigh',
      'gpt-5.1-codex-max-xhigh-fast',
      'gpt-5.5-high',
      'gpt-5.5-high-fast',
      'claude-opus-4-7-thinking-high',
      'claude-4.6-opus-high-thinking',
      'claude-4.6-opus-high-thinking-fast',
      'gpt-5.5-none',
      'gpt-5.5-none-fast',
      'gpt-5.5-low',
      'gpt-5.5-low-fast',
      'gpt-5.5-medium',
      'gpt-5.5-medium-fast',
      'gpt-5.5-extra-high',
      'gpt-5.5-extra-high-fast',
      'claude-4.6-sonnet-medium',
      'claude-4.6-sonnet-medium-thinking',
      'claude-opus-4-7-low',
      'claude-opus-4-7-low-fast',
      'claude-opus-4-7-medium',
      'claude-opus-4-7-medium-fast',
      'claude-opus-4-7-high',
      'claude-opus-4-7-high-fast',
      'claude-opus-4-7-xhigh',
      'claude-opus-4-7-xhigh-fast',
      'claude-opus-4-7-max',
      'claude-opus-4-7-max-fast',
      'claude-opus-4-7-thinking-low',
      'claude-opus-4-7-thinking-low-fast',
      'claude-opus-4-7-thinking-medium',
      'claude-opus-4-7-thinking-medium-fast',
      'claude-opus-4-7-thinking-high-fast',
      'claude-opus-4-7-thinking-xhigh',
      'claude-opus-4-7-thinking-xhigh-fast',
      'claude-opus-4-7-thinking-max',
      'claude-opus-4-7-thinking-max-fast',
      'grok-4.3',
      'gpt-5.4-low',
      'gpt-5.4-high',
      'gpt-5.4-high-fast',
      'gpt-5.4-medium',
      'gpt-5.4-medium-fast',
      'gpt-5.4-xhigh',
      'gpt-5.4-xhigh-fast',
      'claude-4.6-opus-high',
      'claude-4.6-opus-max',
      'claude-4.6-opus-max-thinking',
      'claude-4.6-opus-max-thinking-fast',
      'claude-4.5-opus-high',
      'claude-4.5-opus-high-thinking',
      'gpt-5.2-low',
      'gpt-5.2-low-fast',
      'gpt-5.2-fast',
      'gpt-5.2-high',
      'gpt-5.2-high-fast',
      'gpt-5.2-xhigh',
      'gpt-5.2-xhigh-fast',
      'gemini-3.1-pro',
      'gpt-5.4-mini-none',
      'gpt-5.4-mini-low',
      'gpt-5.4-mini-medium',
      'gpt-5.4-mini-high',
      'gpt-5.4-mini-xhigh',
      'gpt-5.4-nano-none',
      'gpt-5.4-nano-low',
      'gpt-5.4-nano-medium',
      'gpt-5.4-nano-high',
      'gpt-5.4-nano-xhigh',
      'claude-4.5-sonnet',
      'claude-4.5-sonnet-thinking',
      'gpt-5.1-low',
      'gpt-5.1',
      'gpt-5.1-high',
      'gemini-3-flash',
      'gpt-5.1-codex-mini-low',
      'gpt-5.1-codex-mini',
      'gpt-5.1-codex-mini-high',
      'claude-4-sonnet',
      'claude-4-sonnet-thinking',
      'gpt-5-mini',
      'kimi-k2.5',
    ],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    vendor: 'Anomaly',
    description: 'Open-source coding agent with provider/model routing.',
    modelIds: [
      'opencode/big-pickle',
      'opencode/gpt-5-nano',
      'opencode/minimax-m2.5-free',
      'opencode/nemotron-3-super-free',
      'openai/gpt-5.5',
      'openai/gpt-5.5-pro',
      'openai/gpt-5.4',
      'openai/gpt-5.4-pro',
      'openai/gpt-5.4-mini',
      'openai/gpt-5.4-nano',
      'openai/gpt-5.3-codex',
      'openai/gpt-5.3-codex-spark',
      'openai/gpt-5.2',
      'openai/gpt-5.2-codex',
      'openai/gpt-5.1-codex',
      'openai/gpt-5.1-codex-max',
      'openai/gpt-5.1-codex-mini',
      'openai/gpt-5-codex',
      'openai/codex-mini-latest',
      'opencode/gemini-3.1-pro',
      'opencode/gemini-3-flash',
      'opencode/minimax-m2.7',
      'opencode/kimi-k2.6',
      'opencode/glm-5.1',
      'opencode/deepseek-v4-flash-free',
      'opencode/ring-2.6-1t-free',
    ],
  },
  {
    id: 'qwen',
    name: 'Qwen',
    vendor: 'Alibaba',
    description: 'Open-weight model. Good for self-hosted deployments.',
    modelIds: ['qwen3.6-plus', 'qwen3.5-plus', 'qwen3-coder-plus', 'qwen3-max-2026-01-23'],
  },
] as const;

export type AgentModelProviderId = (typeof AGENT_MODEL_PROVIDERS)[number]['id'];

export function getAgentModelDefinition(model: string | null | undefined) {
  return AGENT_MODEL_PROVIDERS.find((provider) => provider.id === model);
}

export function getAgentModelDefaultId(model: string | null | undefined): string {
  return getAgentModelDefinition(model)?.modelIds[0] ?? '';
}

export function getAgentModelOptions(
  model: string | null | undefined,
  currentModelId?: string | null,
): string[] {
  const baseOptions: string[] = [...(getAgentModelDefinition(model)?.modelIds ?? [])];
  if (!currentModelId || baseOptions.includes(currentModelId)) {
    return baseOptions;
  }
  return [currentModelId, ...baseOptions];
}
